version: '2'
services:
  db:
    build:
      context: https://github.com/rottoza/dockerfiles.git
      dockerfile: Dockerfile-mysql-build    
    volumes:
      - .:/files
    command: --max_allowed_packet=32505856
  php:
    build:
      context: https://github.com/rottoza/dockerfiles.git
      dockerfile: Dockerfile-php-build
    volumes:
      - .:/var/www
    ports:
      - "9001:9001"
    depends_on:
      - db
    links:
      - db:mysql
      - mail:mail
  web:
    build:      
      context: https://github.com/rottoza/dockerfiles.git
      dockerfile: Dockerfile-apache-build    
    volumes:
      - .:/var/www
    ports:
      - "8080:80"
    depends_on:
      - php
    links:
      - db:mysql
      - php:php
  mail:
    build:
      context: ./config
      dockerfile: Dockerfile-mailhog-build
    ports:
      - "1025:1025"
      - "8025:8025"
