version: '2'
services:
  db:
    build:
      context: https://github.com/rottoza/dockerfiles.git
      dockerfile: Dockerfile-mysql-build    
    volumes:
      - .:/files
    command: --max_allowed_packet=32505856
  web:
    build:
      context: https://github.com/rottoza/dockerfiles.git
      dockerfile: Dockerfile-apache-php-build    
    volumes:
      - .:/var/www
    ports:
      - "8080:80"
    depends_on:
      - db
    links:
      - db:mysql
