version: '2'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql-build    
    volumes:
      - .:/files
    command: --max_allowed_packet=32505856
  php:
    build:
      context: .
      dockerfile: Dockerfile-php-build
    volumes:
      - .:/var/www    
    depends_on:
      - db
    links:
      - db:mysql
  web:
    build:      
      context: .
      dockerfile: Dockerfile-apache-build    
    volumes:
      - .:/var/www
    ports:
      - "8080:80"
    depends_on:
      - php
    links:
      - db:mysql
      - php:php
