FROM ubuntu:16.04 
RUN apt-get update && apt-get install -y apache2 \
  php \
  php-mysql \
  libapache2-mod-php \
  php-mcrypt \
  php-cli \
  php-curl \
  php-gd \
  php-zip \
  php-xml \
  php-mbstring \
  php-xdebug \
  less \  
  git \
  wget \
  vim \
  mysql-client \
  curl
RUN a2enmod rewrite
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer
RUN export DRUSH_LATEST_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/drush-ops/drush/releases/latest)
RUN export DRUSH_LATEST_VERSION=$(echo $DRUSH_LATEST_RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
RUN export DRUSH_ARTIFACT_URL="https://github.com/drush-ops/drush/releases/download/$DRUSH_LATEST_VERSION/drush.phar"
RUN wget $DRUSH_ARTIFACT_URL
RUN chmod +x drush.phar
RUN mv drush.phar /usr/local/bin/drush
COPY apache2-foreground /usr/local/bin/
COPY 000-default.conf /etc/apache2/sites-available/
RUN chmod +x /usr/local/bin/apache2-foreground
CMD ["/usr/local/bin/apache2-foreground"]
