FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y apache2 \
  php \
  php-mysql \
  libapache2-mod-php \
  php-mcrypt \
  php-cli \
  php-curl \
  php-gd \
  php-zip \
  php-xml \
  php-mbstring \
  less \
  nano \
  git \
  wget
RUN a2enmod rewrite
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer
CMD ["apache2ctl", "-D", "FOREGROUND"]
