FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y apache2 \
  php \
  php-mysql \
  libapache2-mod-php \
  php-mcrypt \
  php-cli \
  php-curl \
  php-gd \
  php-zip \
  php-xml \
  php-mbstring \
  php-xdebug \
  less \  
  git \
  wget \
  vim \
  mysql-client
RUN a2enmod rewrite
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer
COPY apache2-foreground /usr/local/bin/
COPY 000-default.conf /etc/apache2/sites-available/
RUN chmod +x /usr/local/bin/apache2-foreground
CMD ["/usr/local/bin/apache2-foreground"]
